import '../styles/tabs.css';

export default function SettingsTab({ history, onClearHistory }) {
  const handleExport = (calc) => {
    const content = `NM Dose Helper – Calculation Report
====================================
Date & Time: ${calc.timestamp}

PATIENT
Weight: ${calc.patientWeight ? calc.patientWeight + ' kg' : 'N/A'}
Age: ${calc.patientAgeYears ? calc.patientAgeYears + ' years' : 'N/A'}
${calc.patientHeight ? `Height: ${calc.patientHeight} cm` : ''}
${calc.patientAgeMonths ? `Age (months): ${calc.patientAgeMonths}` : ''}

TRACER: ${calc.tracer.name} (${calc.tracer.nuclide})
Indication: ${calc.tracer.indication}

DOSE CALCULATION
----------------
Webster factor: ${calc.websterFactor.toFixed(3)}
Adult nominal dose (Webster): ${calc.nominalMci.toFixed(2)} mCi
After Webster caps: ${calc.websterCappedMci.toFixed(2)} mCi
${calc.pediatricApplied ? `Pediatric rule: ${calc.pediatricRule}\nPediatric factor: ${calc.pediatricFactor.toFixed(3)}x` : 'No pediatric adjustment'}
FINAL DOSE: ${calc.finalMci.toFixed(2)} mCi

Range allowed: ${calc.tracer.minMci.toFixed(1)} – ${calc.tracer.maxMci.toFixed(1)} mCi
${calc.ageWarning ? `\n⚠️ ${calc.ageWarning}` : ''}

DISCLAIMER
For reference only. Verify with institutional protocols.
Generated by NM Dose Helper (2024 guidelines)`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NM_Dose_${calc.tracer.name.replace(/\s+/g, '_')}_${new Date(calc.timestamp).toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    URL.revokeObjectURL(url);
    document.body.removeChild(a);
  };

  const handleClearAll = () => {
    if (window.confirm('Delete all calculation history? This cannot be undone.')) onClearHistory();
  };

  return (
    <div className="tab-content settings-tab">
      <h2>Settings</h2>
      <p className="section-description">Calculation history</p>
      <div className="settings-section">
        <div className="settings-header"><h3>History</h3>{history.length > 0 && <button className="clear-all-button" onClick={handleClearAll}>Clear All</button>}</div>
        {history.length > 0 ? (
          <>
            <p className="history-count">{history.length} calculation(s) saved</p>
            <div className="history-list">
              {history.map((calc, idx) => (
                <div key={idx} className="history-item">
                  <div className="history-header">
                    <div className="history-info"><h4>{calc.tracer.name}</h4><p className="history-date">{calc.timestamp}</p></div>
                    <div className="history-dose"><span className="dose-value">{calc.finalMci.toFixed(1)} mCi</span></div>
                  </div>
                  <div className="history-details">
                    <div className="detail-row"><span className="detail-label">Weight:</span><span className="detail-value">{calc.patientWeight} kg</span></div>
                    <div className="detail-row"><span className="detail-label">Age:</span><span className="detail-value">{calc.patientAgeYears ?? '—'}</span></div>
                    {calc.pediatricApplied && <div className="detail-row"><span className="detail-label">Rule:</span><span className="detail-value">{calc.pediatricRule}</span></div>}
                    <div className="detail-row"><span className="detail-label">Factor:</span><span className="detail-value">{calc.pediatricFactor.toFixed(3)}x</span></div>
                  </div>
                  <button className="export-button" onClick={() => handleExport(calc)}>📥 Export</button>
                </div>
              ))}
            </div>
          </>
        ) : (
          <div className="empty-state"><p className="empty-title">No calculations yet</p><p className="empty-description">Your history appears here</p></div>
        )}
      </div>
      <div className="settings-section about-section">
        <h3>About</h3>
        <div className="about-grid">
          <div className="about-item"><span className="about-label">Version</span><span className="about-value">3.0 (2024 guidelines)</span></div>
          <div className="about-item"><span className="about-label">Tracers</span><span className="about-value">30+</span></div>
          <div className="about-item"><span className="about-label">Rules</span><span className="about-value">Automated</span></div>
        </div>
      </div>
      <div className="disclaimer-box"><p>⚠️ <strong>Disclaimer:</strong> For reference only. Always verify doses.</p></div>
    </div>
  );
}